FROM nginx:latest
LABEL maintainer 'copy'

RUN echo '<h1> Sem conteudo </h2>'  C:\Users\helder.santos\Documents\docker_new\build-com-copy\conteudo.html
COPY *.html C:\Users\helder.santos\Documents\docker_new\build-com-copy