#versao do compose
version: "3"

#volumes
volumes:
    dados:

#redes
networks:
    banco:
    web:
    fila:

#servicos
services:
    db:
        image: postgres:9.6
        volumes:
            # Vaolume dos dados
            - dados:/var/lib/postgresql/data
            #Scripst
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks: 
            - banco
    frontend:
        image: nginx:1.13
        volumes:
            #site
            - ./web/:/usr/share/nginx/html/
            #configuração do proxy reverso 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks: 
            - web
        depends_on: 
            - app
    app:
        #aplicacao
        image: python:3.6
        volumes:
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        networks: 
            - banco
            - web
            - fila
        depends_on: 
            - db
            - queue

        environment: 
            - DB_NAME=email_sender
    queue:
        image: redis:3.2
        networks: 
            - fila
    worker:
        build: worker
        volumes: 
        #worker
        - ./worker:/worker
        working_dir: /worker
        command: worker.py
        networks:
            - fila
        depends_on: 
            - queue
